title: BODYBAG: RUN, SHIFT, SYNC
description: 짬통 트랜스휴머니즘 OSR
remote_theme: just-the-docs/just-the-docs@v0.12.0

url: https://bipedalocto.github.io/BODYBAGRPG/

color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
